### ISSUE TITLE
Something is wrong with latest Reddit links

### ISSUE THREAD

**Issue by TwentyFiveEx** [ccbrown/gggtracker#101]
The latest Reddit links are linking back to the wrong url: They are linking back to the official site, when it looks like they should be linking to Reddit.

Example, Nick_GGG post shows it's for r/pathofexile but the link is wrong.

![image](https://user-images.githubusercontent.com/109299419/180098829-920680a8-2486-4c42-83ec-16598ea097e5.png)

**Comment by ccbrown** [comment]
This is by design. That Reddit post was a link, not a text, submission. So the tracker does the same thing Reddit itself does: when you click the title, you go to the linked website.

If you want to go to the comments for that Reddit post, you can click the little Snoo to the left of the title.

Maybe there's a better design that could be implemented here, but at the moment it's working as it always has and as intended.
